spring:
  application:
    name: config-server
      #（加入密码认证）
      #security:
      # user:
      # name: 'admin'
    # password: 'admin'
  cloud:
    config:
      server:
        #远程仓库
        #git:
          #git仓库的地址；
          #uri: https://github.com/xub1997/cloud.git
          #discovery:
            #enabled: true
        #本地仓库
        native:
          search-locations: classpath:/config

  profiles:
    active: native

server:
  port: 5000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /actuator/info
      #（加入密码认证）
      #metadata-map:
      #user.name: ${spring.security.user.name}
    # user.password: ${spring.security.user.password}
    appname: config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"

