
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  dialect: mysql
  pageSizeZero: true
  reasonable: true
  supportMethodsArguments: true

#mybatis
mybatis:
  #映射文件位置
  mapper-locations: classpath:mapper/*.xml
  #实体类包位置
  type-aliases-package: com.beidou.position.entity
mapper:
  mappers: com.beidou.position.common.IBaseMapper
  not-empty: false
  identity: MYSQL
server:
  port: 9001
