spring:
  #应用名
  application:
    name: gateway

server:
  #端口
  port: 7000
  #访问路径
  servlet:
    context-path: /




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /swagger-ui.html
    prefer-ip-address: true

#路由配置
zuul:
  ignoredServices: '*'
  #HTTP请求头不进行转发
  sensitive-headers: Cookie,Set-Cookie,Authorization
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200

  routes:

    api-1:
      path: /api/v1/user/**
      serviceId: user
    api-2:
      path: /api/v1/beidou/**
      serviceId: beidou

#打开feign-hystrix
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"

