spring:
  #应用名
  application:
    name: gateway
  redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1
      timeout: 0
server:
  #端口
  port: 7000
  #访问路径
  servlet:
    context-path: /




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /swagger-ui.html
    prefer-ip-address: true

#路由配置
zuul:
  ignoredServices: '*'
  #HTTP请求头不进行转发
  sensitive-headers: Cookie,Set-Cookie,Authorization
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200

  routes:


    api-1:
      path: /api/v1/logger/**
      serviceId: logger



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"

mybatis:
  typeAliasesPackage: com.beidou.gateway.entity
  mapperLocations: classpath:mapper/*.xml

