spring:
  #应用名
  application:
    name: logger
  security:
    user:
      name: 'admin'
      password: 'admin'

server:
  #端口号
  port: 4001

#mybatis:
  #mybatis的mapper.xml文件的路径
  #type-aliases-package: com.beidou.lqx.car_manager.model
  #mybatis的mapper.xml文件的路径
  #mapper-locations: .\src\main\java\com\beidou\lqx\car_manager\mapper\*.xml

eureka:
  client:
    #向eureka注册服务
    register-with-eureka: true
    #服务检索
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@register1:8001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@register2:8002/eureka/
  instance:
    #每隔10秒发送心跳
    leaseRenewalIntervalInSeconds: 10
    #检测链接
    health-check-url-path: /actuator/health
    #状态链接
    statusPageUrlPath: /actuator/info



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"


mybatis:
  typeAliasesPackage: com.beidou.logger.entity
  mapperLocations: classpath:mapper/*.xml