#端口
server:
  port: 8081

spring:
  #应用名
  application:
    name: user
      #（加入密码认证）
      #security:
      # user:
      # name: 'admin'
    # password: 'admin'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://localhost:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    statusPageUrlPath: /actuator/info
      #（加入密码认证）
      #metadata-map:
      #user.name: ${spring.security.user.name}
    # user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml

info:
  app:
    name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
    description: "@project.description@"
    version: "@project.version@"
    author: "许b"


mybatis:
  typeAliasesPackage: com.beidou.user.entity
  mapperLocations: classpath:mapper/*.xml

#pagehelper分页插件
#pagehelper:
  #mysql方言
  #helperDialect: mysql
  #参数有理化
  #reasonable: true
  #supportMethodsArguments: true
  #params: count=countSql
#redis:
  #shiro:
   # host: 127.0.0.1
    #port: 6379
    #timeout: 0
    #password:
feign:
  hystrix:
    enabled: true